config/routes.rb
Rails.application.routes.draw do
  root to: "users#index"
  devise_for :users

  resources :posts, except: :index
  resources :users, only: :show
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  validates :post, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :posts

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]

  def index
  end

  def new
    @post = Post.new
  end

  def create
    @user = User.find(current_user.id)
    @post = @user.posts.new(post_params)
    if @post.save
      respond_to do |format|
        format.html do
          flash[:success] = "Post successfully added"
          redirect_to root_path
        end
        format.js
      end
    else
      flash[:danger] = "There was a problem creating your listing, please try again."
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @user = User.find(current_user.id)
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:success] = "Post successfully updated"
      redirect_to user_path(@user)
    end
  end

  def destroy
    @user = User.find(current_user.id)
    @post = Post.find(params[:id])
    @post.destroy
    respond_to do |format|
      format.html do
        flash[:danger] = "Post successfully deleted"
        redirect_to user_path(@user)
      end
      format.js
    end
  end

private
  def post_params
    params.require(:post).permit(:post)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @posts = Post.all.reverse
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <ul class="main-nav list-unstyled">
          <li><%= link_to "Jitter", root_path, class: 'navbar-brand' %></li>
        </ul>
      </div>
      <ul class="nav navbar-nav navbar-left">
        <% if user_signed_in? %>
          <li>Logged in as: <strong><%= link_to current_user.email, user_path(current_user) %></strong></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>

  <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>

    <%= yield %>
  </div>

</body>
</html>

app/views/posts/_form.html.erb
<%= render "layouts/errors", object: @post %>

<%= form_for @post, remote: true do |f| %>
  <%= f.label :post %>
  <%= f.text_area :post, class: 'form-control', size: "30x6", required: true, autofocus: true %>
  <br>
  <%= f.submit class: 'btn btn-success', method: "update" %>
<% end %>

app/views/posts/_post.html.erb
<div class="<%= post.id %>"
  <hr>
  <%= post.user.email %><br>
  <%= post.post %>
  <% if current_user = @user %>
    <%= link_to "DELETE", post_path(post.id), remote: true, class: "btn btn-xs btn-danger",
                                              data: {confirm: "You sure?",
                                                     method: 'delete'}%>
  <% end %>
  <hr>
</div>

app/views/posts/create.js.erb
$('#new_post').remove();
$('#new_link').show();
$('#feed').prepend('<%= j render(@post) %>');

app/views/posts/destroy.js.erb
$(".<%= @post.id %>").remove();

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

app/views/posts/new.js.erb
$('#new_link').hide().after('<%= j render("form") %>');

app/views/users/index.html.erb
<h1>Welcome to Jitter!</h1>

<%= link_to "Add Post", new_post_path, id: "new_link", remote: true %>

<% if @posts.any? %>
  <h4>Here are some posts:</h4>
  <div id="feed">
    <%= render @posts %>
  </div>
<% else %>
  <p>There are no posts yet!</p>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.email %></h1>

<% if @user.posts.any? %>
  <h4>Here are some posts:</h4>
  <div id="feed">
    <%= render @user.posts %>
  </div>
<% else %>
  <p>There are no posts yet!</p>
<% end %>